### ISSUE TITLE
TWBR is not a STM32 register

### ISSUE THREAD

**Issue by alexandreviau303** [hwstar/MCP4726#1]
https://github.com/hwstar/MCP4726/blob/d3d5a661ef8ded4b3097386ed77e663707909ff7/MCP4726.cpp#L66-L73
This library is not working with platformio and a Nucleo board, because TWBR is not a STM32 register. I believe the I2C speed should be choose by the user, using Wire.setClock(().

**Comment by consume-all** [comment]
Just ran across this issue myself whilst trying to use this library with a RP2040. I believe that when this library was made Wire.setClock() was still undeveloped. Now-a-days, it is! I am using this and it compiles thus far..

```    void MCP4726::setVoltage( uint16_t output)
    {
     /* uint8_t twbrback = TWBR;
    TWBR = 12; // 400 khz
    //  TWBR = 72; // 100 khz
    */
    Wire.setClock(400000);
    Wire.beginTransmission(_i2caddr);
    Wire.write((uint8_t) ((output >> 8) & 0x0F));   // MSB: (D11, D10, D9, D8)
    Wire.write((uint8_t) (output));  // LSB: (D7, D6, D5, D4, D3, D2, D1, D0)
    Wire.endTransmission();
    Wire.setClock(100000);
    /*TWBR = twbrback;*/
    }
